language: generic

os: osx
osx_image: xcode9.3

env:
  global:
    - COLUMNS=240
    - PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig:/usr/local/opt/jpeg-turbo/lib/pkgconfig:$PKG_CONFIG_PATH"

before_install:
  - ./setup.sh

script:
  - ./package.sh

before_cache:
  - ./cleanup.sh

cache:
  directories:
    # Cache downloaded bottles
    - $HOME/Library/Caches/Homebrew

addons:
  artifacts:
    s3_region: eu-west-1
